# Generated by Django 5.1.2 on 2024-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
