# Generated by Django 5.1.2 on 2024-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
