# Generated by Django 5.1.2 on 2024-10-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
