# Generated by Django 5.1.2 on 2024-11-04 19:03

import account.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام تعاونی')),
                ('registration_code', models.CharField(help_text='کد ثبت رسمی تعاونی', max_length=128, unique=True, verbose_name='کد ثبت رسمی')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[account.validators.phone_validator], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('vehicle_count', models.IntegerField(default=0, verbose_name='تعداد ماشین\u200cها')),
                ('driver_count', models.IntegerField(default=0, verbose_name='تعداد رانندگان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('cooperative_manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدیر تعاونی')),
            ],
            options={
                'verbose_name': 'تعاونی',
                'verbose_name_plural': 'تعاونی\u200cها',
                'db_table': 'Cooperative',
            },
        ),
    ]
