# Generated by Django 5.1.2 on 2024-10-26 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('canceled', 'canceled')], default='scheduled', max_length=128)),
                ('ticket_price', models.IntegerField()),
                ('total_seats', models.SmallIntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.cities')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicles')),
            ],
            options={
                'verbose_name': 'travle',
                'verbose_name_plural': 'travles',
                'db_table': 'Travel',
            },
        ),
    ]
