# Generated by Django 5.1.2 on 2024-11-25 20:15

import django.core.validators
import django.db.models.deletion
import validations.validations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=10, unique=True, validators=[validations.validations.licence_plate_validator], verbose_name='شماره پلاک')),
                ('model', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1380)], verbose_name='سال تولید')),
                ('capacity', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='ضرفیت')),
                ('vehicle_type', models.CharField(max_length=255, verbose_name='نوع ماشین')),
                ('color', models.CharField(blank=True, max_length=254, null=True, verbose_name='رنگ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperatives.cooperatives', verbose_name='تعاونی مربوطه')),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'ماشین\u200cها',
                'db_table': 'Vehicle',
            },
        ),
    ]
