# Generated by Django 5.1.2 on 2024-10-29 15:53

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_first_name', models.CharField(max_length=60)),
                ('leader_last_name', models.CharField(max_length=128)),
                ('leader_phone_number', models.CharField(max_length=12, validators=[account.validators.phone_validator])),
                ('leader_national_code', models.IntegerField()),
                ('tracking_code', models.IntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'db_table': 'Reservation',
            },
        ),
    ]
